import { loadProfiles } from "../components/data.js";

export async function HomePage(root) {
  const card = document.createElement("div");
  card.className = "grid";

  let profiles = [];
  try {
    profiles = await loadProfiles();
  } catch (e) {
    root.innerHTML = `<div class="card"><div class="h1">Data error</div><div class="small">${e?.message || e}</div></div>`;
    return;
  }

  const sorted = [...profiles].sort((a,b) => String(a.name).localeCompare(String(b.name)));

  const left = document.createElement("div");
  left.className = "card";

  left.innerHTML = `
    <div class="h1">Profile Archive</div>
    <div class="small">Static profiles generated by the <a href="https://github.com/epsilver/cei-cli" target="_blank" rel="noopener">cei-cli utility</a>. Tap a record to view the full report.</div>
    <div class="hr"></div>
    <div class="search">
      <input id="q" placeholder="Search profiles..." />
      <button class="btn" id="goCompare">Compare</button>
    </div>
    <div class="list" id="list"></div>
  `;

  const right = document.createElement("div");
  right.className = "card";
  right.innerHTML = `
    <div class="h1">Methodology</div>
    <div class="small">Heuristic keyword scoring across five behavioral and ideological axes. Scores are derived from Wikipedia lead sections and Wikidata occupation tags.</div>

    <div class="hr"></div>
    <div class="h1" style="font-size:13px;margin-bottom:8px">Five-Axis Signal Wheel</div>
    <div class="list" style="margin-top:0;gap:0">
      <div class="item" style="flex-direction:column;gap:2px"><div class="section-title">Establishment</div><div class="meta">Alignment with institutional power, governance, and mainstream systems.</div></div>
      <div class="item" style="flex-direction:column;gap:2px"><div class="section-title">Justice</div><div class="meta">Emphasis on rights, equity, and anti-discrimination framing.</div></div>
      <div class="item" style="flex-direction:column;gap:2px"><div class="section-title">Tradition</div><div class="meta">Preference for continuity, nationalism, and heritage narratives.</div></div>
      <div class="item" style="flex-direction:column;gap:2px"><div class="section-title">Conflict</div><div class="meta">Tolerance for confrontation, controversy, and culture-war engagement.</div></div>
      <div class="item" style="flex-direction:column;gap:2px"><div class="section-title">Rigidity</div><div class="meta">Tendency toward absolutism, purity politics, and rejection of compromise.</div></div>
    </div>

    <div class="hr"></div>
    <div class="h1" style="font-size:13px;margin-bottom:8px">CEI Tier Scale</div>
    <div class="list" style="margin-top:0;gap:0">
      <div class="item"><div class="left"><b>Minimal</b><div class="meta">0 – 20</div></div><div class="pill">Low deviation</div></div>
      <div class="item"><div class="left"><b>Moderate</b><div class="meta">21 – 40</div></div><div class="pill">Mild signal</div></div>
      <div class="item"><div class="left"><b>Elevated</b><div class="meta">41 – 60</div></div><div class="pill">Clear profile</div></div>
      <div class="item"><div class="left"><b>High</b><div class="meta">61 – 80</div></div><div class="pill">Strong signal</div></div>
      <div class="item"><div class="left"><b>Extreme</b><div class="meta">81 – 100</div></div><div class="pill">Maximum deviation</div></div>
    </div>

    <div class="hr"></div>
    <div class="h1" style="font-size:13px;margin-bottom:8px">Primary Lean</div>
    <div class="small">A deterministic classifier derived from axis deltas. <b>Woke</b> indicates progressive-leaning signal dominance. <b>Chud</b> indicates reactionary-leaning signal dominance.</div>
  `;

  card.appendChild(left);
  card.appendChild(right);
  root.appendChild(card);

  const list = left.querySelector("#list");
  const q = left.querySelector("#q");
  const goCompare = left.querySelector("#goCompare");

  function render(items) {
    list.innerHTML = "";
    for (const p of items) {
      const item = document.createElement("a");
      item.className = "item";
      item.href = `#/profile/${encodeURIComponent(p.slug)}`;

      const ceiVal = p?.cei?.value;
      const tier = p?.cei?.tier;
      const pill = (ceiVal != null && tier) ? `CEI ${ceiVal} | ${tier}` : (p?.status || "PROFILE");

      const lean = p?.primaryLean || "N/A";

      item.innerHTML = `
        <div class="left">
          <div><b>${p.name}</b></div>
          <div class="meta">Primary Lean: ${lean}</div>
        </div>
        <div class="pill">${pill}</div>
      `;
      list.appendChild(item);
    }
  }

  render(sorted);

  q.addEventListener("input", () => {
    const term = q.value.trim().toLowerCase();
    if (!term) return render(sorted);
    render(sorted.filter(p => String(p.name).toLowerCase().includes(term) || String(p.slug).toLowerCase().includes(term)));
  });

  goCompare.addEventListener("click", () => { location.hash = "#/compare"; });
}